# Generated by Django 5.2.8 on 2025-12-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Model1Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_level", models.CharField(max_length=20)),
                ("maintenance_indicator", models.CharField(max_length=10)),
                ("air_temperature_kelvin", models.FloatField()),
                ("process_temperature_kelvin", models.FloatField()),
                ("rotational_speed_rpm", models.FloatField()),
                ("torque_nm", models.FloatField()),
                ("tool_wear_min", models.FloatField()),
                ("temp_difference", models.FloatField()),
                ("speed_torque_ratio", models.FloatField()),
                ("wear_rate", models.FloatField()),
                ("energy_index", models.FloatField()),
                ("thermal_stress_index", models.FloatField()),
                ("torque_wear_product", models.FloatField()),
                ("speed_temp_interaction", models.FloatField()),
                ("normalized_wear_rate", models.FloatField()),
                ("predicted_class", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model2Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_condition", models.CharField(max_length=20)),
                ("melt_temperature", models.FloatField()),
                ("mold_temperature", models.FloatField()),
                ("casting_pressure", models.FloatField()),
                ("cooling_time", models.FloatField()),
                ("flow_rate", models.FloatField()),
                ("ambient_humidity", models.FloatField()),
                ("operator_experience", models.FloatField()),
                ("temp_diff", models.FloatField()),
                ("cooling_pressure_ratio", models.FloatField()),
                ("flow_temp_product", models.FloatField()),
                ("predicted_defect", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
