# Generated by Django 5.2.8 on 2025-11-28 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quali_defect_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model1record",
            old_name="air_temperature",
            new_name="air_temperature_kelvin",
        ),
        migrations.RenameField(
            model_name="model1record",
            old_name="process_temperature",
            new_name="process_temperature_kelvin",
        ),
        migrations.RenameField(
            model_name="model1record",
            old_name="rotational_speed",
            new_name="rotational_speed_rpm",
        ),
        migrations.RenameField(
            model_name="model1record",
            old_name="tool_wear",
            new_name="tool_wear_min",
        ),
        migrations.RenameField(
            model_name="model1record",
            old_name="torque",
            new_name="torque_nm",
        ),
    ]
