"""
Django settings for qualisense_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 1. SECURITY: Use a fallback for local dev so 'runserver' doesn't crash
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-local-dev-key-change-this-in-prod")

# 2. DEBUG: True locally, False on Render
# If the 'RENDER' env var exists (Render sets this auto), DEBUG is False.
DEBUG = 'RENDER' not in os.environ


# 3. CSRF: Trust your Render URL to allow form submissions (Login/Admin)
# Replace 'qualisense' with your exact Render app name if it's different
CSRF_TRUSTED_ORIGINS = [
    'https://qualisense.onrender.com',
]

ALLOWED_HOSTS = ['*']


SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'quali_defect_app',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "qualisense_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # You can add global template folder here later
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qualisense_project.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mydb",
        "USER": "postgres",
        'PASSWORD': os.environ.get('DB_LOCAL_PASSWORD', 'Niru@9391'),
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Override if DATABASE_URL is provided (Render + Neon)
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL and DATABASE_URL.strip() != "":
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True
    )

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -----------------------------------------
# 🔥 STATIC FILES (CSS, JS, IMAGES)
# -----------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'



# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
